// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqL2fplOpC1FlV-rqv8GoKwHe29XDOfoM',
    appId: '1:352997835473:web:2df0b3886a9ede32787bf0',
    messagingSenderId: '352997835473',
    projectId: 'flutternotesapp-577c9',
    authDomain: 'flutternotesapp-577c9.firebaseapp.com',
    storageBucket: 'flutternotesapp-577c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIwehl-dxoQdUcXlGszdwh38L4QbZa8ec',
    appId: '1:352997835473:android:2cdedb8da4bd6ea5787bf0',
    messagingSenderId: '352997835473',
    projectId: 'flutternotesapp-577c9',
    storageBucket: 'flutternotesapp-577c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNazxwfJV7U60U22yGJDV5msXfsuozse0',
    appId: '1:352997835473:ios:217dc762c976bd3a787bf0',
    messagingSenderId: '352997835473',
    projectId: 'flutternotesapp-577c9',
    storageBucket: 'flutternotesapp-577c9.firebasestorage.app',
    iosBundleId: 'com.example.miniprojet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNazxwfJV7U60U22yGJDV5msXfsuozse0',
    appId: '1:352997835473:ios:217dc762c976bd3a787bf0',
    messagingSenderId: '352997835473',
    projectId: 'flutternotesapp-577c9',
    storageBucket: 'flutternotesapp-577c9.firebasestorage.app',
    iosBundleId: 'com.example.miniprojet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqL2fplOpC1FlV-rqv8GoKwHe29XDOfoM',
    appId: '1:352997835473:web:6bce817d5c63f614787bf0',
    messagingSenderId: '352997835473',
    projectId: 'flutternotesapp-577c9',
    authDomain: 'flutternotesapp-577c9.firebaseapp.com',
    storageBucket: 'flutternotesapp-577c9.firebasestorage.app',
  );

}